    IOMUXC_SetPinMux(IOMUXC_ECSPI1_SCLK_GPIO5_IO06, 0U);
    IOMUXC_SetPinMux(IOMUXC_ECSPI1_MOSI_GPIO5_IO07, 0U);
    IOMUXC_SetPinMux(IOMUXC_ECSPI1_MISO_GPIO5_IO08, 0U);
    IOMUXC_SetPinMux(IOMUXC_ECSPI1_SS0_GPIO5_IO09, 0U);
}
